### ISSUE TITLE
kong-oidc or native OP (Operation Provider) adapters ?.

### ISSUE THREAD

**Issue by canattofilipe** [nokia/kong-oidc#163]
Hi all,

I built an authentication infra with kong + kong-oidc + keycloak, this is working fine, but I have seen that keycloak provides some adapters (see [keycloak-client-adapters)](https://www.keycloak.org/docs/latest/securing_apps/index.html#what-are-client-adapters). What are pros and cons about using kong-oidc rather than some keycloak-client-adapters.

**Comment by cristichiru** [comment]
1. One of the biggest advantages IMO is that your protected app does not have to know anything about OIDC/OAUTH, you may not need to configure anything or write any code for it.
Just put a reverse proxy on top, enhanced with a filter plugin like kong-oidc for kong - or openidc-lua-resty for nginx - or [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc) for Apache HTTPD - and you will have instant AuthZ.
2. Another one is that this plugin - and actually the great library [lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc) that powers it - acts as an opaque middleman, so no tokens are exposed to the user-agent, increasing security.
