### ISSUE TITLE
Restrict user request based on scope avilable in token ?

### ISSUE THREAD

**Issue by harsh4870** [nokia/kong-oidc#168]
i have tried scope in the plugin but not working as expected is there any option to restrict user request if certain scope are not present in the token ?

in kong official enterprise plugin there is an option for `scopes_required` anything similar here ?

**Comment by alihossein** [comment]
Hi. how to fix this problem? please share it.  @harsh4870

**Comment by harsh4870** [comment]
@alihossein  i am not sure what you are using exactly however i faced this issue while using this plugin. 

Please use this extended version of the plugin : https://github.com/gbbirkisson/kong-plugin-jwt-keycloak

specific answer : https://github.com/nokia/kong-oidc/issues/135#issuecomment-691249159

Read more at : https://github.com/nokia/kong-oidc/issues/135
