### ISSUE TITLE
Refreshing access token doesn't work as expected

### ISSUE THREAD

**Issue by nbkntu** [nokia/kong-oidc#33]
I have a problem with refreshing access token.
My access token has expiration time of 1 hour.
It seems that the session cookie (supported by lua-resty-session library) also has the same expiration time.

When a request comes in slightly after 1 hour, it should trigger refreshing the access token which has just expired.
However since the session has also expired, a redirect to SSO login would happen to ask the user to re-login instead.

How would I resolve this issue?

My current workaround is to set access_token_expires_leeway to say 10 minutes in the config so refreshing the token can happen before the session expires.
[https://github.com/nokia/kong-oidc/blob/master/kong/plugins/oidc/utils.lua#L52]
However this requires making the field available in the plugin parameter list.

Thanks!

**Comment by Trojan295** [comment]
lua-resty-session uses `ngx.var.session_cookie_lifetime` to calculate the expiration date. You could try to set this variable in your nginx-kong configuration (https://github.com/openresty/lua-nginx-module#ngxvarvariable).

**Comment by nbkntu** [comment]
Yay, setting session_cookie_lifetime in the config works!
Thanks!

**Comment by a-maggioni** [comment]
How did you set "session_cookie_lifetime" in your kong configuration?

**Comment by a-maggioni** [comment]
> Yay, setting session_cookie_lifetime in the config works! Thanks!

How did you set "session_cookie_lifetime" in your kong configuration?
