### ISSUE TITLE
no redirect after logout.

### ISSUE THREAD

**Issue by anselmevignon** [nokia/kong-oidc#36]
After a sucessful logout, the client is not redirected to the login page. That is because:

 - When calling logout, the plugin redirects to discovery.end_session_endpoint with no redirect_uri parameter.
 - No redirect_after_logout_uri parameter is passed to lua-resty-openidc.

One possible fix would be to copy the redirect_uri to the redirect_after_logout_uri parameter. Alternatively, one could add a "redirect_after_logout_uri" parameter to the plugin. 

What do you think ?

**Comment by Trojan295** [comment]
Fallback to `redirect_uri_path` could be a solution, although it's designed to be used after a successful redirect. I think it's better to add an additional parameters, which will be passed to lua-resty-openidc.

**Comment by anselmevignon** [comment]
That makes sense, so adding a redirect_after_logout_uri, with a "null" default would be the prefered solution ?

**Comment by Trojan295** [comment]
I think leaving it as optional and passing only in case is set is fine.
You're welcome to contribute! If you have any questions catch me on gitter on in the room for this project: https://gitter.im/nokia/kong-oidc :)

**Comment by Trojan295** [comment]
Config for redirect_after_logout_uri was merged. Closing this.
