### ISSUE TITLE
upgrade lua-resty-openidc

### ISSUE THREAD

**Issue by zhangyuan** [nokia/kong-oidc#40]
The latest lua-resty-openidc is 1.5.3, while the kong-oidc depends on "lua-resty-openidc ~> 1.4.0-1". 

Several issues have been fixed since then. For example allow optional SSL verification https://github.com/zmartzone/lua-resty-openidc/issues/125

Can you please upgrade that? Thanks.

BTW, I'm using Okta as OIDC provider.

**Comment by ror6ax** [comment]
Hi, thanks for reporting that. We are looking into updating it soon!

**Comment by Trojan295** [comment]
PR #41 merged. @zhangyuan thanks!
