### ISSUE TITLE
Kong 0.13 support

### ISSUE THREAD

**Issue by xwrs** [nokia/kong-oidc#43]
Kong 0.13 provides features as Service and Route instead of obsolete API entity. It would be nice to have this plugin to be "attached" to particular route or service objects.

**Comment by ror6ax** [comment]
Hi @xwrs, thanks for raising this! We will be looking into that.

**Comment by Trojan295** [comment]
Haven't checked this now, but are there problems with kong-oidc, when you register them on routes or services?

**Comment by xwrs** [comment]
Works with services. Not tested with routes though. 
Even though it is not documented, but it seems that plugin works with services as it did with APIs.
