### ISSUE TITLE
config.client_secret required what about public oidc?

### ISSUE THREAD

**Issue by devdavidkarlsson** [nokia/kong-oidc#46]
config.client_secret=required 

Meaning this plugin cannot be used for APIs with public oidc client, meaning where the client_secret isn't sent at all.

Also it cannot be used when multiple clients are to consume the api, since only one client_id, secret pair is set.

Thanks.

**Comment by Trojan295** [comment]
Is this a feature request?

The plugin was developed to support the OIDC Authorization Code Flow and in this case the client secret should be used. Kong can be considered as an backend serving content, so the Authorization Code Flow is recommended.

**Comment by devdavidkarlsson** [comment]
We are not using kong as a backend, but an API gateway. 
I think the [JWT plugin ](https://gist.github.com/fsargent/47b9bc678ab197a62ce5a186f67e269e)may better suit or use-cases.

Thanks.

**Comment by Trojan295** [comment]
Yeah, I know, but you can consider Kong as a proxy to your backends. That's why is supports the Authorization Code Flow. Implementing other flows on Kong is a bit pointless pointless.

**Comment by Trojan295** [comment]
@devdavidkarlsson, can we close this ticket in favor of #54?
