### ISSUE TITLE
Non-ascii char is not escaped in X-Userinfo header

### ISSUE THREAD

**Issue by nbkntu** [nokia/kong-oidc#52]
X-Userinfo header is rejected by the sever (running [Kestrel](https://github.com/aspnet/KestrelHttpServer)/.NET core 2) when it contains non-ascii character, for example when user last name contains special character "é".

The plugin is calling [`cjson.encode()`](https://github.com/nokia/kong-oidc/blob/029a7e93068e016fb5a992b0ead7274319e838d4/kong/plugins/oidc/handler.lua#L43) which preserves non-ascii chars. ([doc](https://www.kyne.com.au/~mark/software/lua-cjson-manual.html#encode))

Currently there's no workaround, except updating the user info last name to avoid using special characters.

Is there other better way to get around this?
Could we update the code to escape non-ascii/unicode chars?

**Comment by Trojan295** [comment]
Fix in #56. Closing
