### ISSUE TITLE
Recent version bumps not found in git tags or luarocks repo

### ISSUE THREAD

**Issue by tommilligan** [nokia/kong-oidc#60]
Just trying to get up and running with the plugin (looks like great work!), and noticed that the newer options such as `bearer_only` are not available in the luarocks repo.

For the last couple of version bumps:
- 1.0.5
- 1.1.0

there do not appear to have been any git tags or uploads to luarocks.

I don't have sight over if/how the upload process is automated, but happy to help out in any way I can? This is currently preventing me from doing an install of the latest rock (first time with lua, so if there's an obvious solution to this do let me know)

**Comment by krehm** [comment]
I ran into this same issue.  What I ended up doing in the kong Dockerfile was change the 'luarocks install' command to 'luarocks make kong-oidc-1.1.0-0.rockspec' which caused it to use my local directory instead of pulling it down from a server.   This should hold you until somone adds the missing tags.

**Comment by tommilligan** [comment]
@krehm thanks for the tip of `luarocks make`, I *knew* I must be missing something obvious.

At the moment I'm building from my fork due to the slow response time, but I'll still be submitting PRs back to here eventually

**Comment by Trojan295** [comment]
I don't have permission on LuaRocks to upload a new version.

@phirvone @tsyrjanen , could you handle this and release from the current master?

**Comment by phirvone** [comment]
v1.1.0 now released and uploaded to luarocks (in luarocks version is 1.1.0-0).
