### ISSUE TITLE
Automate Testing Infrastructure

### ISSUE THREAD

**Issue by jerneyio** [nokia/kong-oidc#80]
The goal here is to automate the following using docker-compose:

> Start Keycloak and Kong's db, wait till it's ready, run the db migration (uncomment the command in docker-compose.yml, start Kong and run setup.py. The source code in mounted into the container, so you need only to restart Kong's container to test your changes.

This way the tests and infrastructure they run on can be executed using a single command.

**Comment by JoshTheGoldfish** [comment]
Got the build working with one command. How are the tests run once the services are running and setup.py has been run?

**Comment by JoshTheGoldfish** [comment]
As far as I could tell, there are no tests to run (yet) after setup.py has been run.

For unit tests, I created a docker image that can run the unit tests. That way, all developers can run them in exactly the same environment (these were crashing on my Mac, previously). PR should be in by the end of the day.
