### ISSUE TITLE
Support for Service with new Routes and Services entities

### ISSUE THREAD

**Issue by ronaldxl** [nokia/kong-oidc#82]
Hello,

Firstly, thanks for the great work!

I hope to know if the plugin has support for Service with new Routes and Services entities

Thanks.

**Comment by Trojan295** [comment]
Yes, it support the new entities. You register the plugin on a serivce instead of a api (see eg. https://github.com/nokia/kong-oidc/blob/de67ea0ae8f23e1931b4d08e9e8efe5493f4501a/test/docker/integration/setup.py#L123)
