### ISSUE TITLE
Redirection loop

### ISSUE THREAD

**Issue by tsyrjanen** [nokia/kong-oidc#9]
In kong-oidc-1.0.1-0.rockspec there is

dependencies = {
  "lua-resty-openidc ~> 1.2.3-1"
}

that brings too old version, 1.2.1 of openidc.lua

That might cause redirection loop.

**Comment by tsyrjanen** [comment]
lua-resty-openidc ~> 1.4.0-1

That seems to fix the issue.

**Comment by hoaivan** [comment]
latest lua-resty-session 2.18 is needed as well. Old version of it causes redirection loop on mine.
