### ISSUE TITLE
Kong 1.0.0 support

### ISSUE THREAD

**Issue by SolarisYan** [nokia/kong-oidc#92]
Do you plan to support Kong 1.0.0 or have support now?

**Comment by shamsalmon** [comment]
I believe nokia already developed something separately for that

**Comment by jerneyio** [comment]
Curious, why wouldn't this support 1.0.0 already? Has anyone done any testing, yet?

**Comment by Trojan295** [comment]
I tested this and it works also with Kong 1.0.
