### ISSUE TITLE
Client_Credentials and Authorization_Code

### ISSUE THREAD

**Issue by flowdopip** [nokia/kong-oidc#99]
Hi,

Currently, I'm using IdentityServer as an IDP, and follow the documentation when we setup a client with Authorization_Code, the application supports both Client_credentials and authorization_code.

How can i get this with this plugin? 

https://github.com/IdentityServer/IdentityServer3/issues/911

**Comment by Trojan295** [comment]
I'm closing this in favor of #100. See my response there.
